//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ansatt : person {
    
    private string avdelingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string avdeling {
        get {
            return this.avdelingField;
        }
        set {
            this.avdelingField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ansatt))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class person : aktor {
    
    private System.DateTime dodsdatoField;
    
    private bool dodsdatoFieldSpecified;
    
    private landkode dodslandField;
    
    private bool dodslandFieldSpecified;
    
    private string dodsstedField;
    
    private string fodestedField;
    
    private System.DateTime fodselsdatoField;
    
    private bool fodselsdatoFieldSpecified;
    
    private string fulltNavnField;
    
    private kjonn kjonnField;
    
    private bool kjonnFieldSpecified;
    
    private personnavn navnField;
    
    private personnavn opprinneligNavnField;
    
    private sivilstand sivilstandField;
    
    private bool sivilstandFieldSpecified;
    
    private landkode statsborgerskapField;
    
    private bool statsborgerskapFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dodsdato {
        get {
            return this.dodsdatoField;
        }
        set {
            this.dodsdatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dodsdatoSpecified {
        get {
            return this.dodsdatoFieldSpecified;
        }
        set {
            this.dodsdatoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public landkode dodsland {
        get {
            return this.dodslandField;
        }
        set {
            this.dodslandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dodslandSpecified {
        get {
            return this.dodslandFieldSpecified;
        }
        set {
            this.dodslandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dodssted {
        get {
            return this.dodsstedField;
        }
        set {
            this.dodsstedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fodested {
        get {
            return this.fodestedField;
        }
        set {
            this.fodestedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime fodselsdato {
        get {
            return this.fodselsdatoField;
        }
        set {
            this.fodselsdatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fodselsdatoSpecified {
        get {
            return this.fodselsdatoFieldSpecified;
        }
        set {
            this.fodselsdatoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fulltNavn {
        get {
            return this.fulltNavnField;
        }
        set {
            this.fulltNavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public kjonn kjonn {
        get {
            return this.kjonnField;
        }
        set {
            this.kjonnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kjonnSpecified {
        get {
            return this.kjonnFieldSpecified;
        }
        set {
            this.kjonnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personnavn navn {
        get {
            return this.navnField;
        }
        set {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personnavn opprinneligNavn {
        get {
            return this.opprinneligNavnField;
        }
        set {
            this.opprinneligNavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sivilstand sivilstand {
        get {
            return this.sivilstandField;
        }
        set {
            this.sivilstandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sivilstandSpecified {
        get {
            return this.sivilstandFieldSpecified;
        }
        set {
            this.sivilstandFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public landkode statsborgerskap {
        get {
            return this.statsborgerskapField;
        }
        set {
            this.statsborgerskapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statsborgerskapSpecified {
        get {
            return this.statsborgerskapFieldSpecified;
        }
        set {
            this.statsborgerskapFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum landkode {
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    DK,
    
    /// <remarks/>
    SE,
    
    /// <remarks/>
    US,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum kjonn {
    
    /// <remarks/>
    KVINNE,
    
    /// <remarks/>
    UKJENT,
    
    /// <remarks/>
    MANN,
    
    /// <remarks/>
    UBESTEMT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class personnavn {
    
    private string etternavnField;
    
    private string fornavnField;
    
    private string mellomnavnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string etternavn {
        get {
            return this.etternavnField;
        }
        set {
            this.etternavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fornavn {
        get {
            return this.fornavnField;
        }
        set {
            this.fornavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mellomnavn {
        get {
            return this.mellomnavnField;
        }
        set {
            this.mellomnavnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class kontaktInformasjon {
    
    private string epostadresseField;
    
    private string mobiltelefonnummerField;
    
    private string telefonnummerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string epostadresse {
        get {
            return this.epostadresseField;
        }
        set {
            this.epostadresseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mobiltelefonnummer {
        get {
            return this.mobiltelefonnummerField;
        }
        set {
            this.mobiltelefonnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string telefonnummer {
        get {
            return this.telefonnummerField;
        }
        set {
            this.telefonnummerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class periode {
    
    private System.DateTime sluttField;
    
    private bool sluttFieldSpecified;
    
    private System.DateTime startField;
    
    private bool startFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime slutt {
        get {
            return this.sluttField;
        }
        set {
            this.sluttField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sluttSpecified {
        get {
            return this.sluttFieldSpecified;
        }
        set {
            this.sluttFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startSpecified {
        get {
            return this.startFieldSpecified;
        }
        set {
            this.startFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class identifikator {
    
    private string identifikatorTypeField;
    
    private string identifikatorVerdiField;
    
    private periode periodeField;
    
    private string utstedtAvAutoritetField;
    
    private System.DateTime utstedtDatoField;
    
    private bool utstedtDatoFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifikatorType {
        get {
            return this.identifikatorTypeField;
        }
        set {
            this.identifikatorTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifikatorVerdi {
        get {
            return this.identifikatorVerdiField;
        }
        set {
            this.identifikatorVerdiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public periode periode {
        get {
            return this.periodeField;
        }
        set {
            this.periodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string utstedtAvAutoritet {
        get {
            return this.utstedtAvAutoritetField;
        }
        set {
            this.utstedtAvAutoritetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime utstedtDato {
        get {
            return this.utstedtDatoField;
        }
        set {
            this.utstedtDatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool utstedtDatoSpecified {
        get {
            return this.utstedtDatoFieldSpecified;
        }
        set {
            this.utstedtDatoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(person))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ansatt))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class aktor {
    
    private identifikator identifikatorField;
    
    private kontaktInformasjon kontaktInformasjonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public identifikator identifikator {
        get {
            return this.identifikatorField;
        }
        set {
            this.identifikatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public kontaktInformasjon kontaktInformasjon {
        get {
            return this.kontaktInformasjonField;
        }
        set {
            this.kontaktInformasjonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum sivilstand {
    
    /// <remarks/>
    GIFT,
    
    /// <remarks/>
    SKILT_PARTNER,
    
    /// <remarks/>
    UOPPGITT,
    
    /// <remarks/>
    SEPARERT_PARTNER,
    
    /// <remarks/>
    UGIFT,
    
    /// <remarks/>
    REGISTRERT_PARTNER,
    
    /// <remarks/>
    SEPARERT,
    
    /// <remarks/>
    ENKE_ELLER_ENKEMANN,
    
    /// <remarks/>
    GJENLEVENDE_PARTNER,
    
    /// <remarks/>
    SKILT,
}
