configuration: Release

before_build:
  - cmd: copy AnsattAdapterAgresso\AppExample.config AnsattAdapterAgresso\App.config
  - cmd: copy AnsattAdapterAgressoTests\AppExample.config AnsattAdapterAgressoTests\App.config
  - nuget restore

test:
  categories:
    except:
      - IntegrationTests